package com.youme.naya.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryBlue = Color(0x2C67FF)
val PrimaryDark = Color(0x122045)
val SecondaryLightBlue = Color(0xDFE6FB)
val SecondaryMediumBlue = Color(0x5C8AFF)
val SecondarySystemBlue = Color(0x0891F2)
val SecondaryDarkBlue = Color(0x055EEA)
val SystemLightRed = Color(0xFFF2F9)
val SystemOrange = Color(0xF57227)
val SystemPink = Color(0xFE647C)
val SystemRed = Color(0xFE3D00)
val SystemLightYellow = Color(0xFFF9DE)
val SystemYellow = Color(0xFEBA00)
val SystemLightGreen = Color(0xEBF9F1)
val SystemGreen = Color(0x3BC171)
val SystemLightPurple = Color(0xF2EFFF)
val SystemPurple = Color(0x7B61FE)
val NeutralWhite = Color(0xFAFAFC)
val NeutralLightness = Color(0xF2F5F9)
val NeutralLight = Color(0xCED3D6)
val NeutralMedium = Color(0xBDC5CA)
val NeutralGray = Color(0xA1ACB3)
val NeutralMetal = Color(0x88929F)
val NeutralDarkGray = Color(0x444657)